### ISSUE TITLE
Наложение оптических искажений на снимки камеры

### ISSUE THREAD

**Issue by zmm** [moevm/cv_dataset_generator#7]
Искажения камеры задаются примерно так:

https://docs.opencv.org/master/dc/dbb/tutorial_py_calibration.html
https://en.wikipedia.org/wiki/Distortion_%28optics%29

@pro100kot  предоставит файл-пример

Необходимо реализовать  наложение искажений на снимок, сделанный в программе.

**Comment by kochaika** [comment]
![image](https://user-images.githubusercontent.com/10850581/109971789-a74cbf80-7d07-11eb-827d-e2cb70e88662.png)
![image](https://user-images.githubusercontent.com/10850581/109971875-c0557080-7d07-11eb-8b00-1ca17958ff07.png)
![image](https://user-images.githubusercontent.com/10850581/109971942-d06d5000-7d07-11eb-8937-4e9c05fbdcbf.png)

**Comment by kochaika** [comment]
```
---
header: 
  seq: 2484
  stamp: 
    secs: 1617642179
    nsecs: 164046764
  frame_id: "autobot10/camera_optical_frame"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [-0.3061830991469583, 0.0655951595031282, -0.0009007345776965652, 0.001687799357074066, 0.0]
K: [338.08101999764006, 0.0, 312.541389823373, 0.0, 337.9751806514881, 231.26322586234303, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [232.69541931152344, 0.0, 314.37258201093937, 0.0, 0.0, 269.1441650390625, 224.0366361245906, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---

```
